import Head from "next/head";

import Image from "next/image";
import Navbar from "../components/Navbar";

import styles from "../styles/Home.module.css";
import Signup from "./Signup";

export default function Home() {
  return (
    <>
      <Navbar />
      <div>
        <div className={styles.container}>
          <Head>
            <title>4e-Store</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className={styles.LeftHome}>
            <p>
              Selamat datang di 4e-Store kami
              <br />
              menyediakan berbagai macam
              <br />
              product sepatu , dengan kualitas
              <br />
              terbaik dan harga terjangkau
            </p>
            <br />
            <br />
            <p>
              Klik product untuk melihat list
              <br />
              barang yang kami miliki !
            </p>
          </div>
          <div className={styles.RightHome}></div>
        </div>
      </div>
    </>
  );
}
